// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: internal/proto/kvlog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*LogEntry_SetCmd
	//	*LogEntry_DeleteCmd
	Cmd           isLogEntry_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_internal_proto_kvlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_kvlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_internal_proto_kvlog_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetCmd() isLogEntry_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *LogEntry) GetSetCmd() *LogEntry_Set {
	if x != nil {
		if x, ok := x.Cmd.(*LogEntry_SetCmd); ok {
			return x.SetCmd
		}
	}
	return nil
}

func (x *LogEntry) GetDeleteCmd() *LogEntry_Delete {
	if x != nil {
		if x, ok := x.Cmd.(*LogEntry_DeleteCmd); ok {
			return x.DeleteCmd
		}
	}
	return nil
}

type isLogEntry_Cmd interface {
	isLogEntry_Cmd()
}

type LogEntry_SetCmd struct {
	SetCmd *LogEntry_Set `protobuf:"bytes,1,opt,name=set_cmd,json=setCmd,proto3,oneof"`
}

type LogEntry_DeleteCmd struct {
	DeleteCmd *LogEntry_Delete `protobuf:"bytes,2,opt,name=delete_cmd,json=deleteCmd,proto3,oneof"`
}

func (*LogEntry_SetCmd) isLogEntry_Cmd() {}

func (*LogEntry_DeleteCmd) isLogEntry_Cmd() {}

type LogEntry_Set struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry_Set) Reset() {
	*x = LogEntry_Set{}
	mi := &file_internal_proto_kvlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry_Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry_Set) ProtoMessage() {}

func (x *LogEntry_Set) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_kvlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry_Set.ProtoReflect.Descriptor instead.
func (*LogEntry_Set) Descriptor() ([]byte, []int) {
	return file_internal_proto_kvlog_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LogEntry_Set) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry_Set) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type LogEntry_Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry_Delete) Reset() {
	*x = LogEntry_Delete{}
	mi := &file_internal_proto_kvlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry_Delete) ProtoMessage() {}

func (x *LogEntry_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_kvlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry_Delete.ProtoReflect.Descriptor instead.
func (*LogEntry_Delete) Descriptor() ([]byte, []int) {
	return file_internal_proto_kvlog_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LogEntry_Delete) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_internal_proto_kvlog_proto protoreflect.FileDescriptor

const file_internal_proto_kvlog_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/kvlog.proto\x12\x05kvdog\"\xc5\x01\n" +
	"\bLogEntry\x12.\n" +
	"\aset_cmd\x18\x01 \x01(\v2\x13.kvdog.LogEntry.SetH\x00R\x06setCmd\x127\n" +
	"\n" +
	"delete_cmd\x18\x02 \x01(\v2\x16.kvdog.LogEntry.DeleteH\x00R\tdeleteCmd\x1a-\n" +
	"\x03Set\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x1a\x1a\n" +
	"\x06Delete\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03keyB\x05\n" +
	"\x03cmdB-Z+github.com/pvcnt/kvdog/internal/proto;protob\x06proto3"

var (
	file_internal_proto_kvlog_proto_rawDescOnce sync.Once
	file_internal_proto_kvlog_proto_rawDescData []byte
)

func file_internal_proto_kvlog_proto_rawDescGZIP() []byte {
	file_internal_proto_kvlog_proto_rawDescOnce.Do(func() {
		file_internal_proto_kvlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_kvlog_proto_rawDesc), len(file_internal_proto_kvlog_proto_rawDesc)))
	})
	return file_internal_proto_kvlog_proto_rawDescData
}

var file_internal_proto_kvlog_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_kvlog_proto_goTypes = []any{
	(*LogEntry)(nil),        // 0: kvdog.LogEntry
	(*LogEntry_Set)(nil),    // 1: kvdog.LogEntry.Set
	(*LogEntry_Delete)(nil), // 2: kvdog.LogEntry.Delete
}
var file_internal_proto_kvlog_proto_depIdxs = []int32{
	1, // 0: kvdog.LogEntry.set_cmd:type_name -> kvdog.LogEntry.Set
	2, // 1: kvdog.LogEntry.delete_cmd:type_name -> kvdog.LogEntry.Delete
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_kvlog_proto_init() }
func file_internal_proto_kvlog_proto_init() {
	if File_internal_proto_kvlog_proto != nil {
		return
	}
	file_internal_proto_kvlog_proto_msgTypes[0].OneofWrappers = []any{
		(*LogEntry_SetCmd)(nil),
		(*LogEntry_DeleteCmd)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_kvlog_proto_rawDesc), len(file_internal_proto_kvlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_kvlog_proto_goTypes,
		DependencyIndexes: file_internal_proto_kvlog_proto_depIdxs,
		MessageInfos:      file_internal_proto_kvlog_proto_msgTypes,
	}.Build()
	File_internal_proto_kvlog_proto = out.File
	file_internal_proto_kvlog_proto_goTypes = nil
	file_internal_proto_kvlog_proto_depIdxs = nil
}
