// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/kvservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{0}
}

func (x *GetItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetItemResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemRequest) Reset() {
	*x = PutItemRequest{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemRequest) ProtoMessage() {}

func (x *PutItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemRequest.ProtoReflect.Descriptor instead.
func (*PutItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{2}
}

func (x *PutItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutItemRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutItemResponse) Reset() {
	*x = PutItemResponse{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutItemResponse) ProtoMessage() {}

func (x *PutItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutItemResponse.ProtoReflect.Descriptor instead.
func (*PutItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{3}
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteItemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_pkg_proto_kvservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_kvservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_kvservice_proto_rawDescGZIP(), []int{5}
}

var File_pkg_proto_kvservice_proto protoreflect.FileDescriptor

const file_pkg_proto_kvservice_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/proto/kvservice.proto\x12\x05kvdog\"\"\n" +
	"\x0eGetItemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"=\n" +
	"\x0fGetItemResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"8\n" +
	"\x0ePutItemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x11\n" +
	"\x0fPutItemResponse\"%\n" +
	"\x11DeleteItemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\x14\n" +
	"\x12DeleteItemResponse2\xc2\x01\n" +
	"\tKVService\x128\n" +
	"\aGetItem\x12\x15.kvdog.GetItemRequest\x1a\x16.kvdog.GetItemResponse\x128\n" +
	"\aPutItem\x12\x15.kvdog.PutItemRequest\x1a\x16.kvdog.PutItemResponse\x12A\n" +
	"\n" +
	"DeleteItem\x12\x18.kvdog.DeleteItemRequest\x1a\x19.kvdog.DeleteItemResponseB(Z&github.com/pvcnt/kvdog/pkg/proto;protob\x06proto3"

var (
	file_pkg_proto_kvservice_proto_rawDescOnce sync.Once
	file_pkg_proto_kvservice_proto_rawDescData []byte
)

func file_pkg_proto_kvservice_proto_rawDescGZIP() []byte {
	file_pkg_proto_kvservice_proto_rawDescOnce.Do(func() {
		file_pkg_proto_kvservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_kvservice_proto_rawDesc), len(file_pkg_proto_kvservice_proto_rawDesc)))
	})
	return file_pkg_proto_kvservice_proto_rawDescData
}

var file_pkg_proto_kvservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_kvservice_proto_goTypes = []any{
	(*GetItemRequest)(nil),     // 0: kvdog.GetItemRequest
	(*GetItemResponse)(nil),    // 1: kvdog.GetItemResponse
	(*PutItemRequest)(nil),     // 2: kvdog.PutItemRequest
	(*PutItemResponse)(nil),    // 3: kvdog.PutItemResponse
	(*DeleteItemRequest)(nil),  // 4: kvdog.DeleteItemRequest
	(*DeleteItemResponse)(nil), // 5: kvdog.DeleteItemResponse
}
var file_pkg_proto_kvservice_proto_depIdxs = []int32{
	0, // 0: kvdog.KVService.GetItem:input_type -> kvdog.GetItemRequest
	2, // 1: kvdog.KVService.PutItem:input_type -> kvdog.PutItemRequest
	4, // 2: kvdog.KVService.DeleteItem:input_type -> kvdog.DeleteItemRequest
	1, // 3: kvdog.KVService.GetItem:output_type -> kvdog.GetItemResponse
	3, // 4: kvdog.KVService.PutItem:output_type -> kvdog.PutItemResponse
	5, // 5: kvdog.KVService.DeleteItem:output_type -> kvdog.DeleteItemResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_kvservice_proto_init() }
func file_pkg_proto_kvservice_proto_init() {
	if File_pkg_proto_kvservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_kvservice_proto_rawDesc), len(file_pkg_proto_kvservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_kvservice_proto_goTypes,
		DependencyIndexes: file_pkg_proto_kvservice_proto_depIdxs,
		MessageInfos:      file_pkg_proto_kvservice_proto_msgTypes,
	}.Build()
	File_pkg_proto_kvservice_proto = out.File
	file_pkg_proto_kvservice_proto_goTypes = nil
	file_pkg_proto_kvservice_proto_depIdxs = nil
}
